version: "3.0"
services:
  mysql:
    image: mysql:5.7
    container_name: mysqldjango
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - 33061:3306
    volumes:
      - ./mysql:/var/lib/mysql
